/**
 * The central feature catalog.
 *
 * The usage contract requires features to be registered here before a product
 * ships events for them, and forbids a product repository from owning its own
 * list. Until now the registry did not exist, so a `featureKey` was the only
 * thing a screen could show — and `dot-class.author.lesson-save` is an
 * identifier, not something a reader recognises. A key answers "which feature";
 * only a registered label answers "what is it".
 *
 * The key stays the stable identity. The label is presentation and may be
 * rewritten freely; the key may not, because rewriting it breaks every stored
 * event that carries it.
 */
export interface FeatureDefinition {
  /** Stable `<product>.<surface>.<capability>` identity. */
  readonly key: string;
  /** What a person calls this feature. */
  readonly label: string;
  /** Producing product. */
  readonly product: string;
  /** Work area inside the product — author, report, editor, play. */
  readonly surface: string;
  /** What the user completed, in one sentence. */
  readonly description: string;
  /** Optional label for summed `outcome.count`, such as pages or affected pins. */
  readonly quantityLabel?: string;
  readonly status: "proposed" | "active" | "deprecated" | "retired";
}

/** Product identity, so a screen does not print `dot-mini-games` at a reader. */
export const productLabels: Readonly<Record<string, string>> = {
  "dot-canvas": "Dot Canvas",
  "dot-class": "Dot Class",
  "dot-cloud": "Dot Cloud",
  "dot-document": "Dot Document",
  "dot-hub": "Dot Hub",
  "dot-mini-games": "Dot Mini Games",
  "dot-music": "Dot Music",
  "dot-quiz": "Dot Quiz",
  "dot-space": "Dot Space",
  "dot-travel": "Dot Travel",
};

export const featureCatalog = {
  "dot-canvas.editor.command": {
    key: "dot-canvas.editor.command",
    label: "편집 명령",
    product: "dot-canvas",
    surface: "편집기",
    description: "캔버스에서 실행한 편집 명령을 완료한다.",
    quantityLabel: "변경 돌기",
    status: "active",
  },
  "dot-canvas.editor.tool-select": {
    key: "dot-canvas.editor.tool-select",
    label: "도구 선택",
    product: "dot-canvas",
    surface: "편집기",
    description: "그리기·도형·점자 등 편집 도구를 선택한다.",
    status: "active",
  },
  "dot-canvas.navigation.menu-open": {
    key: "dot-canvas.navigation.menu-open",
    label: "도구 메뉴 열기",
    product: "dot-canvas",
    surface: "탐색",
    description: "도구 그룹 메뉴를 열어 기능을 탐색한다.",
    status: "active",
  },
  "dot-canvas.output.dotpad-print": {
    key: "dot-canvas.output.dotpad-print",
    label: "DOT PAD 출력",
    product: "dot-canvas",
    surface: "출력",
    description: "현재 페이지나 발표 화면을 DOT PAD로 출력한다.",
    quantityLabel: "출력 페이지",
    status: "active",
  },
  "dot-class.author.lesson-save": {
    key: "dot-class.author.lesson-save",
    label: "교재 저장",
    product: "dot-class",
    surface: "교재 만들기",
    description: "교사가 만든 교재를 저장해 수업에서 쓸 수 있게 한다.",
    quantityLabel: "교재 단계",
    status: "active",
  },
  "dot-class.author.template-apply": {
    key: "dot-class.author.template-apply",
    label: "서식 적용",
    product: "dot-class",
    surface: "교재 만들기",
    description: "미리 만들어 둔 서식을 교재에 적용한다.",
    status: "active",
  },
  "dot-class.author.bulk-edit": {
    key: "dot-class.author.bulk-edit",
    label: "단계 일괄 편집",
    product: "dot-class",
    surface: "교재 만들기",
    description: "여러 교재 단계를 한 번에 변경한다.",
    quantityLabel: "변경 단계",
    status: "active",
  },
  "dot-class.author.preview": {
    key: "dot-class.author.preview",
    label: "교재 미리보기",
    product: "dot-class",
    surface: "교재 만들기",
    description: "학생에게 보일 교재를 미리 확인한다.",
    status: "active",
  },
  "dot-class.class.session-start": {
    key: "dot-class.class.session-start",
    label: "수업 시작",
    product: "dot-class",
    surface: "수업",
    description: "교사가 실시간 수업을 시작한다.",
    status: "active",
  },
  "dot-class.student.assignment-open": {
    key: "dot-class.student.assignment-open",
    label: "과제 열기",
    product: "dot-class",
    surface: "학생",
    description: "학생이 배정된 과제를 연다.",
    quantityLabel: "과제 활동",
    status: "active",
  },
  "dot-class.student.assignment-submit": {
    key: "dot-class.student.assignment-submit",
    label: "과제 제출",
    product: "dot-class",
    surface: "학생",
    description: "학생이 과제를 완료해 제출한다.",
    quantityLabel: "제출 활동",
    status: "active",
  },
  "dot-class.student.hand-raise": {
    key: "dot-class.student.hand-raise",
    label: "도움 요청",
    product: "dot-class",
    surface: "학생",
    description: "학생이 수업 중 교사에게 도움을 요청한다.",
    status: "active",
  },
  "dot-class.report.csv-export": {
    key: "dot-class.report.csv-export",
    label: "CSV 내보내기",
    product: "dot-class",
    surface: "보고서",
    description: "수업 기록을 표 파일로 내려받는다.",
    status: "active",
  },
  "dot-class.class.voice-broadcast": {
    key: "dot-class.class.voice-broadcast",
    label: "음성 방송",
    product: "dot-class",
    surface: "수업",
    description: "수업 중 교사의 음성을 학생 기기로 보낸다.",
    status: "active",
  },
  "dot-cloud.drive.file-open": {
    key: "dot-cloud.drive.file-open",
    label: "파일 열기",
    product: "dot-cloud",
    surface: "드라이브",
    description: "클라우드에 있는 파일을 연다.",
    status: "active",
  },
  "dot-cloud.drive.file-upload": {
    key: "dot-cloud.drive.file-upload",
    label: "파일 올리기",
    product: "dot-cloud",
    surface: "드라이브",
    description: "내 기기의 파일을 클라우드에 올린다.",
    quantityLabel: "올린 파일",
    status: "active",
  },
  "dot-cloud.drive.file-download": {
    key: "dot-cloud.drive.file-download",
    label: "파일 내려받기",
    product: "dot-cloud",
    surface: "드라이브",
    description: "클라우드의 파일을 내 기기로 내려받는다.",
    quantityLabel: "내려받은 파일",
    status: "active",
  },
  "dot-cloud.drive.folder-create": {
    key: "dot-cloud.drive.folder-create",
    label: "폴더 만들기",
    product: "dot-cloud",
    surface: "드라이브",
    description: "파일을 정리할 폴더를 만든다.",
    status: "active",
  },
  "dot-cloud.drive.file-rename": {
    key: "dot-cloud.drive.file-rename",
    label: "이름 바꾸기",
    product: "dot-cloud",
    surface: "드라이브",
    description: "파일이나 폴더의 이름을 바꾼다.",
    status: "active",
  },
  "dot-cloud.drive.file-move": {
    key: "dot-cloud.drive.file-move",
    label: "파일 옮기기",
    product: "dot-cloud",
    surface: "드라이브",
    description: "파일이나 폴더를 다른 위치로 옮긴다.",
    quantityLabel: "옮긴 파일",
    status: "active",
  },
  "dot-cloud.drive.file-delete": {
    key: "dot-cloud.drive.file-delete",
    label: "휴지통으로 보내기",
    product: "dot-cloud",
    surface: "드라이브",
    description: "파일이나 폴더를 휴지통으로 보낸다.",
    quantityLabel: "버린 파일",
    status: "active",
  },
  "dot-cloud.drive.file-share": {
    key: "dot-cloud.drive.file-share",
    label: "파일 공유",
    product: "dot-cloud",
    surface: "드라이브",
    description: "파일이나 폴더를 다른 사용자와 공유한다.",
    status: "active",
  },
  "dot-cloud.drive.search": {
    key: "dot-cloud.drive.search",
    label: "검색",
    product: "dot-cloud",
    surface: "드라이브",
    description: "이름이나 태그로 파일을 찾는다.",
    status: "active",
  },
  "dot-cloud.drive.favorite-add": {
    key: "dot-cloud.drive.favorite-add",
    label: "즐겨찾기 추가",
    product: "dot-cloud",
    surface: "드라이브",
    description: "자주 쓰는 파일을 즐겨찾기에 넣는다.",
    status: "active",
  },
  "dot-cloud.drive.collection-create": {
    key: "dot-cloud.drive.collection-create",
    label: "컬렉션 만들기",
    product: "dot-cloud",
    surface: "드라이브",
    description: "여러 파일을 묶어 보는 컬렉션을 만든다.",
    status: "active",
  },
  "dot-cloud.drive.tag-edit": {
    key: "dot-cloud.drive.tag-edit",
    label: "태그 편집",
    product: "dot-cloud",
    surface: "드라이브",
    description: "파일에 붙은 분류 태그를 고친다.",
    status: "active",
  },
  "dot-cloud.comms.chat-send": {
    key: "dot-cloud.comms.chat-send",
    label: "대화 보내기",
    product: "dot-cloud",
    surface: "소통",
    description: "친구나 그룹에 대화를 보낸다.",
    quantityLabel: "보낸 대화",
    status: "active",
  },
  "dot-cloud.shell.accessibility-mode": {
    key: "dot-cloud.shell.accessibility-mode",
    label: "접근성 모드",
    product: "dot-cloud",
    surface: "셸",
    description: "고대비 같은 화면 모드를 켜고 끈다.",
    status: "active",
  },
  "dot-cloud.shell.language-change": {
    key: "dot-cloud.shell.language-change",
    label: "언어 변경",
    product: "dot-cloud",
    surface: "셸",
    description: "화면에 쓰는 언어를 바꾼다.",
    status: "active",
  },
  "dot-document.editor.braille-convert": {
    key: "dot-document.editor.braille-convert",
    label: "점자 변환",
    product: "dot-document",
    surface: "편집기",
    description: "문서를 점자로 조판한다.",
    status: "active",
  },
  "dot-document.editor.document-export": {
    key: "dot-document.editor.document-export",
    label: "문서 내보내기",
    product: "dot-document",
    surface: "편집기",
    description: "조판 결과를 지정한 형식으로 내보낸다.",
    status: "active",
  },
  "dot-hub.shell.app-open": {
    key: "dot-hub.shell.app-open",
    label: "앱 열기",
    product: "dot-hub",
    surface: "셸",
    description: "허브에서 위성앱을 열어 실행한다.",
    status: "active",
  },
  "dot-hub.account.sign-in": {
    key: "dot-hub.account.sign-in",
    label: "로그인",
    product: "dot-hub",
    surface: "계정",
    description: "허브 계정으로 로그인한다.",
    status: "active",
  },
  "dot-hub.comms.chat-send": {
    key: "dot-hub.comms.chat-send",
    label: "대화 보내기",
    product: "dot-hub",
    surface: "소통",
    description: "친구나 그룹에 대화를 보낸다.",
    quantityLabel: "보낸 대화",
    status: "active",
  },
  "dot-hub.comms.friend-add": {
    key: "dot-hub.comms.friend-add",
    label: "친구 추가",
    product: "dot-hub",
    surface: "소통",
    description: "다른 사용자를 친구로 추가한다.",
    status: "active",
  },
  "dot-hub.comms.group-create": {
    key: "dot-hub.comms.group-create",
    label: "그룹 만들기",
    product: "dot-hub",
    surface: "소통",
    description: "여러 명이 함께 쓰는 대화 그룹을 만든다.",
    status: "active",
  },
  "dot-hub.shell.settings-change": {
    key: "dot-hub.shell.settings-change",
    label: "설정 변경",
    product: "dot-hub",
    surface: "셸",
    description: "표시와 소리 같은 사용 환경 설정을 바꾼다.",
    status: "active",
  },
  "dot-hub.shell.accessibility-mode": {
    key: "dot-hub.shell.accessibility-mode",
    label: "접근성 모드",
    product: "dot-hub",
    surface: "셸",
    description: "고대비 같은 화면 모드를 켜고 끈다.",
    status: "active",
  },
  "dot-hub.shell.language-change": {
    key: "dot-hub.shell.language-change",
    label: "언어 변경",
    product: "dot-hub",
    surface: "셸",
    description: "화면에 쓰는 언어를 바꾼다.",
    status: "active",
  },
  "dot-hub.device.dotpad-connection": {
    key: "dot-hub.device.dotpad-connection",
    label: "닷패드 연결",
    product: "dot-hub",
    surface: "장치",
    description: "닷패드와 연결하거나 연결이 끊긴다.",
    status: "active",
  },
  "dot-mini-games.play.game-round": {
    key: "dot-mini-games.play.game-round",
    label: "게임 한 판",
    product: "dot-mini-games",
    surface: "플레이",
    description: "게임 한 판을 끝까지 진행한다.",
    status: "active",
  },
  "dot-mini-games.device.dotpad-connection": {
    key: "dot-mini-games.device.dotpad-connection",
    label: "닷패드 연결",
    product: "dot-mini-games",
    surface: "장치",
    description: "닷패드와 연결하거나 연결이 끊긴다.",
    status: "active",
  },
  "dot-mini-games.shell.accessibility-mode": {
    key: "dot-mini-games.shell.accessibility-mode",
    label: "접근성 모드",
    product: "dot-mini-games",
    surface: "셸",
    description: "고대비 같은 화면 모드를 켜고 끈다.",
    status: "active",
  },
  "dot-music.learn.score-read": {
    key: "dot-music.learn.score-read",
    label: "악보 읽기",
    product: "dot-music",
    surface: "배우기",
    description: "점자 악보를 열어 읽는다.",
    status: "active",
  },
  "dot-music.learn.chord-practice": {
    key: "dot-music.learn.chord-practice",
    label: "화음 연습",
    product: "dot-music",
    surface: "배우기",
    description: "화음을 듣고 손으로 확인하며 연습한다.",
    status: "active",
  },
  "dot-music.make.melody-station": {
    key: "dot-music.make.melody-station",
    label: "멜로디 만들기",
    product: "dot-music",
    surface: "만들기",
    description: "음을 이어 붙여 멜로디를 만든다.",
    status: "active",
  },
  "dot-music.make.loop-station": {
    key: "dot-music.make.loop-station",
    label: "루프 연주",
    product: "dot-music",
    surface: "만들기",
    description: "반복되는 소리를 겹쳐 연주한다.",
    status: "active",
  },
  "dot-music.make.ensemble": {
    key: "dot-music.make.ensemble",
    label: "합주",
    product: "dot-music",
    surface: "만들기",
    description: "여러 악기 소리를 함께 울리는 합주를 구성한다.",
    status: "active",
  },
  "dot-music.make.work-save": {
    key: "dot-music.make.work-save",
    label: "작업물 저장",
    product: "dot-music",
    surface: "만들기",
    description: "만든 멜로디나 합주를 클라우드에 저장한다.",
    status: "active",
  },
  "dot-music.play.memory-game": {
    key: "dot-music.play.memory-game",
    label: "멜로디 기억 놀이",
    product: "dot-music",
    surface: "놀이",
    description: "들려준 멜로디를 기억해 따라 누르는 놀이를 한다.",
    status: "active",
  },
  "dot-music.shell.accessibility-mode": {
    key: "dot-music.shell.accessibility-mode",
    label: "접근성 모드",
    product: "dot-music",
    surface: "셸",
    description: "고대비 같은 화면 모드를 켜고 끈다.",
    status: "active",
  },
  "dot-music.shell.language-change": {
    key: "dot-music.shell.language-change",
    label: "언어 변경",
    product: "dot-music",
    surface: "셸",
    description: "화면에 쓰는 언어를 바꾼다.",
    status: "active",
  },
  "dot-music.device.dotpad-connection": {
    key: "dot-music.device.dotpad-connection",
    label: "닷패드 연결",
    product: "dot-music",
    surface: "장치",
    description: "닷패드와 연결하거나 연결이 끊긴다.",
    status: "active",
  },
  "dot-quiz.play.single-round": {
    key: "dot-quiz.play.single-round",
    label: "혼자 풀기 한 판",
    product: "dot-quiz",
    surface: "플레이",
    description: "혼자 퀴즈 한 판을 끝까지 진행한다.",
    quantityLabel: "푼 문항",
    status: "active",
  },
  "dot-quiz.play.multi-round": {
    key: "dot-quiz.play.multi-round",
    label: "함께 풀기 한 판",
    product: "dot-quiz",
    surface: "플레이",
    description: "여러 명이 같은 문제를 푸는 퀴즈 한 판을 진행한다.",
    quantityLabel: "푼 문항",
    status: "active",
  },
  "dot-quiz.room.join": {
    key: "dot-quiz.room.join",
    label: "방 참여",
    product: "dot-quiz",
    surface: "방",
    description: "PIN으로 함께하기 방에 들어간다.",
    status: "active",
  },
  "dot-quiz.room.invite": {
    key: "dot-quiz.room.invite",
    label: "친구 초대",
    product: "dot-quiz",
    surface: "방",
    description: "친구를 함께하기 방으로 초대한다.",
    status: "active",
  },
  "dot-quiz.author.quiz-save": {
    key: "dot-quiz.author.quiz-save",
    label: "문제 저장",
    product: "dot-quiz",
    surface: "문제 만들기",
    description: "만든 문제를 저장해 다시 쓸 수 있게 한다.",
    quantityLabel: "저장 문항",
    status: "active",
  },
  "dot-quiz.author.shape-draw": {
    key: "dot-quiz.author.shape-draw",
    label: "도형 그리기",
    product: "dot-quiz",
    surface: "문제 만들기",
    description: "문제에 넣을 촉각 도형을 그린다.",
    status: "active",
  },
  "dot-quiz.shell.accessibility-mode": {
    key: "dot-quiz.shell.accessibility-mode",
    label: "접근성 모드",
    product: "dot-quiz",
    surface: "셸",
    description: "고대비 같은 화면 모드를 켜고 끈다.",
    status: "active",
  },
  "dot-quiz.shell.language-change": {
    key: "dot-quiz.shell.language-change",
    label: "언어 변경",
    product: "dot-quiz",
    surface: "셸",
    description: "화면에 쓰는 언어를 바꾼다.",
    status: "active",
  },
  "dot-quiz.device.dotpad-connection": {
    key: "dot-quiz.device.dotpad-connection",
    label: "닷패드 연결",
    product: "dot-quiz",
    surface: "장치",
    description: "닷패드와 연결하거나 연결이 끊긴다.",
    status: "active",
  },
  "dot-space.explore.galaxy": {
    key: "dot-space.explore.galaxy",
    label: "은하 탐험",
    product: "dot-space",
    surface: "탐험",
    description: "은하의 형태를 촉각으로 훑어 본다.",
    status: "active",
  },
  "dot-space.explore.star": {
    key: "dot-space.explore.star",
    label: "항성 탐험",
    product: "dot-space",
    surface: "탐험",
    description: "개별 항성의 크기와 온도를 비교한다.",
    status: "active",
  },
  "dot-space.explore.constellation": {
    key: "dot-space.explore.constellation",
    label: "별자리 탐험",
    product: "dot-space",
    surface: "탐험",
    description: "별을 잇는 선을 따라 별자리를 짚는다.",
    status: "active",
  },
  "dot-space.explore.planet-system": {
    key: "dot-space.explore.planet-system",
    label: "행성계 탐험",
    product: "dot-space",
    surface: "탐험",
    description: "태양계와 외계 행성계를 위에서 본 배치로 살핀다.",
    status: "active",
  },
  "dot-space.explore.night-sky": {
    key: "dot-space.explore.night-sky",
    label: "지금 하늘 보기",
    product: "dot-space",
    surface: "탐험",
    description: "지구에서 지금 보이는 하늘을 확인한다.",
    status: "active",
  },
  "dot-space.audio.space-sound": {
    key: "dot-space.audio.space-sound",
    label: "우주의 소리 듣기",
    product: "dot-space",
    surface: "오디오",
    description: "펄서와 공명 사슬 같은 우주의 소리를 듣는다.",
    status: "active",
  },
  "dot-space.shell.accessibility-mode": {
    key: "dot-space.shell.accessibility-mode",
    label: "접근성 모드",
    product: "dot-space",
    surface: "셸",
    description: "고대비 같은 화면 모드를 켜고 끈다.",
    status: "active",
  },
  "dot-space.shell.language-change": {
    key: "dot-space.shell.language-change",
    label: "언어 변경",
    product: "dot-space",
    surface: "셸",
    description: "화면에 쓰는 언어를 바꾼다.",
    status: "active",
  },
  "dot-space.device.dotpad-connection": {
    key: "dot-space.device.dotpad-connection",
    label: "닷패드 연결",
    product: "dot-space",
    surface: "장치",
    description: "닷패드와 연결하거나 연결이 끊긴다.",
    status: "active",
  },
  "dot-travel.map.place-explore": {
    key: "dot-travel.map.place-explore",
    label: "장소 탐험",
    product: "dot-travel",
    surface: "지도",
    description: "관광지 한 곳을 촉각 지도로 탐험한다.",
    status: "active",
  },
  "dot-travel.map.world-explore": {
    key: "dot-travel.map.world-explore",
    label: "세계 지도 탐험",
    product: "dot-travel",
    surface: "지도",
    description: "세계 지도 탐험 모드를 이용한다.",
    status: "active",
  },
  "dot-travel.play.treasure-quiz": {
    key: "dot-travel.play.treasure-quiz",
    label: "보물찾기 퀴즈",
    product: "dot-travel",
    surface: "플레이",
    description: "관광지 보물찾기 퀴즈를 진행한다.",
    quantityLabel: "탐색 장소",
    status: "active",
  },
  "dot-travel.audio.place-story": {
    key: "dot-travel.audio.place-story",
    label: "장소 이야기 듣기",
    product: "dot-travel",
    surface: "오디오",
    description: "선택한 장소의 해설을 재생한다.",
    status: "active",
  },
  "dot-travel.device.dotpad-connection": {
    key: "dot-travel.device.dotpad-connection",
    label: "닷패드 연결",
    product: "dot-travel",
    surface: "장치",
    description: "닷패드와 연결하거나 연결이 끊긴다.",
    status: "active",
  },
} as const satisfies Readonly<Record<string, FeatureDefinition>>;

export type FeatureKey = keyof typeof featureCatalog;

export function getFeatureDefinition(key: string): FeatureDefinition | undefined {
  return (featureCatalog as Readonly<Record<string, FeatureDefinition>>)[key];
}

/**
 * A product's name, or the raw id when it is not registered.
 *
 * Falling back to the id keeps an unregistered product visible instead of
 * dropping it off the screen — an unknown product is a registration gap worth
 * seeing, not something to hide.
 */
export function productLabel(app: string): string {
  return productLabels[app] ?? app;
}
